### PR TITLE
Fix #169 so gosync has the proper DELETE collection behaviour

### LINKED ISSUE #169: Fix incorrect collection delete behaviour
When deleting a collection the behaviour should be: 

* the collection's last-modified timestamp should be reset to 0
* the collection no longer shows up in /info/collections
* last modified timestamp of the entire store should be set to current

### PR DESCRIPTION
**Pull request by mostlygeek**
The logic in db.DeleteCollection was updated to be correct. When a
collection is deleted its last modified timestamp is set to 0 and the
storage level last modified timestamp is set to the current time.

The last modified timestamp at the storage level is now discrete from
the max(last-modified) of collections. It was a wrong assumption that
the two values were always the same.

Unit tests were added to ensure the change in functionality is correct.

### CODE REVIEW

File: syncstorage/db.go [hunk 1]
```diff
@@ -52,6 +52,8 @@ const (
 	// The default TTL is to never expire. Use 100 years
 	// which should be enough (in milliseconds)
 	DEFAULT_BSO_TTL = 100 * 365 * 24 * 60 * 60 * 1000
+
+	STORAGE_LAST_MODIFIED = "Storage Last Modified"
```
Comment (Natim) [inline syncstorage/db.go:56]: Shouldn't the string contain an integer?

**Review by Natim — COMMENTED** [review]
I cannot tell if I understood correctly what you are trying to do there. Also I am not familiar with Go convention just yet. Maybe we can pair review it and you can explain me what's going on?

**Review by rfk — COMMENTED** [review]
My high-level impression of what you're doing here seems solid, but I'm not all up to speed on Go enough to be confident reviewing the details.

File: syncstorage/db.go (hunk 1 above)
Comment (Natim) [reply syncstorage/db.go:56]: Oh it is actually the name of the key that stores the storage last_modified value.

File: syncstorage/db.go [hunk 2]
```diff
@@ -217,23 +219,22 @@ func NewDB(path string, conf *Config) (*DB, error) {
...
-func (d *DB) LastModified() (modified int, err error) {
+// LastModified returns the top level last modified timestamp
+func (d *DB) LastModified() (int, error) {
 	d.Lock()
 	defer d.Unlock()
 
-	var m sql.NullInt64
+	lastMod, err := getKey(d.db, STORAGE_LAST_MODIFIED)
+	if lastMod == "" || err != nil {
+		return 0, err
```
Comment (Natim) [inline syncstorage/db.go:229]: If the value doesn't exists it will return 0, maybe we can scrape the max value to initialize it. and in case of error we will return 0

Comment (mostlygeek) [reply syncstorage/db.go:229]: After thinking about this a bit more, I might leave this code as is. The `lastMod == ""` condition will only happen when: 

- the database is new. No data exists so `0, nil` is a proper response 
- the database is being migrated (before this PR). The next POST, PUT, DELETE will synchronize / fix things anyways. 

In the case of migration: 

- there's only THREE users on the gosync server.  If it's a problem it's probably easier to just migrate the databases. 
- it might not matter to clients, as the storage level timestamp is only returned on `info/*` endpoints. 

@mhammond what would happen on the client side when `GET info/collections`  has a totally wrong `X-Last-Modified` timestamp? Would clients freak out?

Comment (mhammond) [reply syncstorage/db.go:229]: In the current implementation, we don't actually look at x-last-modified of the response itself. We take the last-modified from info/collections, then advance it if the *records* in a get response have a later timestamp. Finally, we use whatever value we end up with to make the POST.

IOW, I expect that if get returns no records, we will do a POST with x-if-unmodified-since of whatever info/collections said the timestamp was.

Comment (mhammond) [reply syncstorage/db.go:229]: Also worth noting is that the local change I had applied which caused this issue is no longer going to be checked in - it was to fix an edge-case to work around a delete followed by a get returning a 404 instead of a 200 - but as we've been discussing, the python server doesn't do the 404 anyway, so the change isn't necessary.

Comment (mostlygeek) [reply syncstorage/db.go:229]: OK that's good to know that it won't totally corrupt your database when I deploy this. :) 
It seems that the python server also has a bug where deletion of a collection then a get doesn't increase the last modified at the whole storage level. :( Fortunately, that bug has been there for a while and it doesn't seem to have caused any major problems.
